config/routes.rb
WeddingPlanner::Application.routes.draw do
  root :to => "pages#home"
  scope "/myconfetti-test" do
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"
    root :to => "pages#home"
    resources :users
    resources :sessions
    resource :budget do
      put 'sort', on: :collection
    end
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :user
  has_many :budget_items, :order=>"position ASC"
  
  accepts_nested_attributes_for :budget_items, :allow_destroy => true, :reject_if => proc { |a| a['description'].blank? }
  attr_accessible :budget_items_attributes

  after_create :set_default_budget_items

  private
  def set_default_budget_items
    default_budget_items = [
      { "description"=>"Insurance",                                 "estimated_cost"=>"110",    "actual_cost"=>"0", "position"=>"1"},
      { "description"=>"The Service",                               "estimated_cost"=>"520",    "actual_cost"=>"0", "position"=>"2"},
      { "description"=>"Reception (venue, food & drinks)",          "estimated_cost"=>"4000",  "actual_cost"=>"0", "position"=>"3"},
      { "description"=>"Evening Reception (venue, food & drinks)",  "estimated_cost"=>"1700",  "actual_cost"=>"0", "position"=>"4"},
      { "description"=>"Entertainment",                             "estimated_cost"=>"850",    "actual_cost"=>"0", "position"=>"5"},
      { "description"=>"Flowers",                                   "estimated_cost"=>"685",    "actual_cost"=>"0", "position"=>"6"},
      { "description"=>"Balloons & Decorations",                    "estimated_cost"=>"460",    "actual_cost"=>"0", "position"=>"7"},
      { "description"=>"The Bride's Outfit",                        "estimated_cost"=>"1590",  "actual_cost"=>"0", "position"=>"8"},
      { "description"=>"Hair and Beauty",                           "estimated_cost"=>"170",    "actual_cost"=>"0", "position"=>"9"},
      { "description"=>"The Groom's Outfit",                        "estimated_cost"=>"200",    "actual_cost"=>"0", "position"=>"10"},
      { "description"=>"Attendants Outfits",                        "estimated_cost"=>"575",    "actual_cost"=>"0", "position"=>"11"},
      { "description"=>"Photography",                               "estimated_cost"=>"905",    "actual_cost"=>"0", "position"=>"12"},
      { "description"=>"Videography",                               "estimated_cost"=>"905",    "actual_cost"=>"0", "position"=>"13"},
      { "description"=>"Transport",                                 "estimated_cost"=>"480",    "actual_cost"=>"0", "position"=>"14"},
      { "description"=>"Stationery",                                "estimated_cost"=>"465",    "actual_cost"=>"0", "position"=>"15"},
      { "description"=>"The Wedding Cake",                          "estimated_cost"=>"370",    "actual_cost"=>"0", "position"=>"16"},
      { "description"=>"Wedding Rings",                             "estimated_cost"=>"630",    "actual_cost"=>"0", "position"=>"17"},
      { "description"=>"Gifts",                                     "estimated_cost"=>"205",    "actual_cost"=>"0", "position"=>"18"},
      { "description"=>"Stag & Hen Nights",                         "estimated_cost"=>"280",    "actual_cost"=>"0", "position"=>"19"},
      { "description"=>"Honeymoon & First night hotel",             "estimated_cost"=>"3400",  "actual_cost"=>"0", "position"=>"20"}
    ]

    default_budget_items.each {|b| self.budget_items.new(b) }
    self.save
  end
end

app/models/budget_item.rb
class BudgetItem < ActiveRecord::Base
  belongs_to :budget
  
  acts_as_list
  
  validates_presence_of :description
  validates_numericality_of :estimated_cost, :actual_cost
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  has_one :budget
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController
  def new
    @budget_item = BudgetItem.new
  end

  def create
    if current_user
      @budget_item = current_user.BudgetItem.new(params[:budget_item])
      if @budget_item.save
        redirect_to budget_path
      else
        render "new"
      end
    end
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_filter :require_login

  def show
    @budget = current_user.budget
  end

  def update
    @budget = current_user.budget
    if @budget.update_attributes(params[:budget])
      redirect_to budget_path, :flash => { :success => "Budget changes saved" }
    else
      redirect_to budget_path, :flash => { :error => "Budget changes were not saved" }
    end
  end

  private

  def require_login
    unless current_user then redirect_to log_in_path end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to budget_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.budget = Budget.new
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budget_helper.rb
module BudgetHelper
end

app/helpers/budget_item_helper.rb
module BudgetItemHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/_budget_item_fields.html.erb
<div class="budget_item">
	<span class="description span-7">
		<%= f.label :description, :class => 'visuallyhidden' %> <%= f.text_field :description, 
			:placeholder => "Description" %>
	</span>
	<span class="estimated_cost span-5">
		<%= f.label :estimated_cost, :class => "span-3" %> 
		<span class="span-2 last">&pound;&nbsp;<%= f.text_field :estimated_cost,
		 	:placeholder => "0" %></span>
	</span>
	<span class="actual_cost span-5">
		<%= f.label :actual_cost, :class => "span-3" %> 
		<span class="span-2 last">&pound;&nbsp;<%= f.text_field :actual_cost, 
			:placeholder => "0" %></span>
	</span>	
	<%= f.hidden_field :position, :class => "position" %>
	<div class="actions span-2 last">
		<%= f.link_to_remove do %>
			<%= image_tag "icons/delete.png" %>
		<% end -%>
		<span class="handle"><%= image_tag "drag-drop-icon.gif" %></span>
	</div>
</div>

app/views/budgets/_form.html.erb
<%= nested_form_for @budget do |f| %>
<div id="budget_headers">
	<div class="span-7" id="description_header">
		<strong>Description</strong> 
	</div>
	<div class="span-5" id="estimated_cost_header">
		<strong>Estimated Cost</strong> 
	</div>
	<div class="span-5 append-2 last" id="actual_cost_header">
		<strong>Actual Cost</strong>
	</div>
</div>
	<div id="budget_items">
		<div class="nested_fields">
			<%= f.fields_for :budget_items %>
		</div>
	</div>
	<div id="budget_live_totals">
		<div id="estimated_total" class="span-5 prepend-7">
			<strong class="span-3"><span>Estimated&nbsp;Total:</span></strong> 
			<span class="span-2 last">&pound;&nbsp;<input type="text" readonly="readonly" /></span>
		</div>
		<div id="actual_total" class="span-5 append-2 last">
			<strong class="span-3">Actual Total:</strong>
			<span class="span-2 last">&pound;&nbsp;<input type="text" readonly=readonly /></span>
		</div>
	</div>
	<p class="form_actions"><%= f.link_to_add :budget_items, :class => "button positive2" do %>
		<%= image_tag "icons/add.png", :title => "title", :class => "class" %> Add a Budget Item 
	<% end %>
	<%= content_tag :button, :type => :submit, :class => :positive2, :style => "margin-right: 0;" do %>
	   <%= image_tag "icons/table_save.png"%> Save Budget
	<% end %>
	</p>
<% end %>

app/views/budgets/show.html.erb
<div id="budget_planner_app">
	<h1>My Budget</h1>
	<%= render :partial => 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
	<head>
 		<title>WeddingPlanner</title>
 		<%= stylesheet_link_tag "application-all", :media => "all" %>
		<%= stylesheet_link_tag "application-print", :media => "print" %>
		<!--[if lte IE 8]>
    	<%= stylesheet_link_tag "application-ie", :media => "all" %>
		<![endif]-->
		<%= stylesheet_link_tag "http://www.confetti.co.uk/css/style.css", :media => "all" %>
 		<%= javascript_include_tag "application" %>
 		<%= csrf_meta_tags %>
 		<script src="http://www.confetti.co.uk/javascripts/modernizr-1.7.min.js"></script>
	</head>
	<body>
		<div id="container" class="container">
			<%= render :partial => 'shared/header' %>

			<div id="content" class="span-19">
				<%= render :partial => 'shared/error_messages' %>

				<%= yield %>

			</div>

			<div id="appmenu" class="span-5 last">
				<%= render :partial => 'shared/app-menu' %>
			</div>

		</div>
		<%= render :partial => 'shared/footer' %>
		<%= yield :javascript %>
	</body> 
</html>

app/views/pages/home.html.erb
<div id="homepage">
	<h1>My Confetti</h1>
	<p>We have the following wedding planning tools available:</p>
	<ul>
		<li><%= link_to "Wedding Budget Planner", budget_path %></li>
	</ul>
	<p><%= link_to "Sign in", log_in_path, :class => "button" %> <%= link_to "Register", sign_up_path, :class => "button" %>
</div>

app/views/shared/_app-menu.html.erb
<div class="sidemenu">
  <p><strong>My Wedding Planner</strong></p>
  <ul>
    <li><a href="#">Dashboard</a></li>
    <li><a href="<%= budget_path %>">Budget planner</a></li>
    <li><a href="#">Guest list &amp; table planner</a>
        <ul>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Guest list</a></li>
          <li><a href="#">Table planner</a></li>
        </ul>
    </li>
    <li><a href="#">Todo list</a></li>
  </ul>
</div>

app/views/shared/_error_messages.html.erb
<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}", :class => "#{name}" %>
<% end %>

app/views/shared/_footer.html.erb
<% require 'open-uri' %>

<%= open("http://www.confetti.co.uk/footer.aspx").read.html_safe %>

app/views/shared/_header.html.erb
<div id="my_confetti_toplinks">
  <div id="user_nav">
    <% if current_user %>
      Logged in as <%= current_user.email %>
			<%= link_to "Log out", log_out_path %>
		<% else %>
			<%= link_to "Sign up", sign_up_path %> or
			<%= link_to "log in", log_in_path %>  
		<% end %>
	</div>
</div>

<% require 'open-uri' %>

<%= open("http://www.confetti.co.uk/header.aspx").read.html_safe %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| -%>
  <% if @user.errors.any? -%>
  	<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages -%>
					<li><%= message %></li>
				<% end -%>
			</ul>
		</div>
  <% end -%>
	<p>
		<%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
	<p class="button"><%= f.submit %></p>
<% end -%>